### ISSUE TITLE
Gw2RaidarUploader.mainWindow.AttemptUpload

### ISSUE THREAD

**Issue by PyRowMan** [CoffeeBns/GW2RaidarUploader#1]
Hey there, I just saw your little soft on reddit and wanted to try it.

Unfortunately, i've got an issue, here is a screen shot of the issue

![capture](https://user-images.githubusercontent.com/6388129/33139872-c8c58a48-cfae-11e7-979e-28efb11028d8.PNG)

**Comment by PyRowMan** [comment]
Well, after a relaunch, it works.

**Comment by CoffeeBns** [comment]
Resolved in the new build.

**Comment by PyRowMan** [comment]
Nice, i'll try that :)
